name: todo_proto
description: Shared protobuf messages and gRPC service definitions for the Todo application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  fixnum: 1.1.1
  grpc: 4.1.0
  protobuf: 4.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  protoc_plugin: 22.5.0
